"""cbom_initial

Revision ID: 82642b151d59
Revises: 001_cbom_initial
Create Date: 2026-03-14 23:26:47.703712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '82642b151d59'
down_revision: Union[str, None] = '001_cbom_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
